---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project-production
  labels:
    app: devops-project
    env: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-project
      env: production
  template:
    metadata:
      labels:
        app: devops-project
        env: production
    spec:
      containers:
      - name: devops-project-container
        image: ayyoubzbd/devops-project:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: devops-project-production-service
  labels:
    app: devops-project
    env: development
spec:
  selector:
    app: devops-project
    env: development
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort